### PR TITLE
Remove repetition

### PR DESCRIPTION
**Pull request by KellerFuchs**
Extracted from #1

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@hashbang/administrators Need somebody to check&merge.

**Comment by RyanSquared** [comment]
lgtm but would prefer someone with more legal power before merging

**Comment by drGrove** [comment]
The original document was created using RocketLawyer, so the repetition may just be a legal thing.

**Comment by RyanSquared** [comment]
If it was legally required, it should have been more exact.

**Review by drGrove — APPROVED** [review]

**Pull request merged**
